### ISSUE TITLE
ID reference prefixed

### ISSUE THREAD

**Issue by woakley** [wikimedia/mediawiki-libs-less.php#76]
Entering this in a less file:
`clip-path: ~"url(#myClip)";
`
Results in:

`clip-path: url(https://example.com/wp-content/themes/theme/assets/css/#myClip);
`
It is interpreting the ID reference as a file, which it isn't.
Can this be fixed/changed please?

**Comment by oncletom** [comment]
See [`clip-path`](https://developer.mozilla.org/fr/docs/Web/CSS/clip-path) documentation, where the URL content can be like `image.svg#symbolId` or `#svgId` (when inlined in the page).

**Comment by Krinkle** [comment]
Imported issue to <https://phabricator.wikimedia.org/T331649>.

Patch submitted for review at <https://gerrit.wikimedia.org/r/c/mediawiki/libs/less.php/+/896143>.

**Comment by Krinkle** [comment]
From [T331649#8684640](https://phabricator.wikimedia.org/T331649#8684640):
> Less_Environment: Treat `url(#myid)` as absolute URL
>
> Commit: 2c271e6a7ffaec177fc92bfd41a17811f40d7d71
> Reviewed-on: https://gerrit.wikimedia.org/r/c/mediawiki/libs/less.php/+/896143
